sudo: required
services:
  - docker

before_install:
  - docker build -t brianbeck/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true brianbeck/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-us-west-2-651266901933"
  bucket-path: "docker-react"
  # only deploy on changes to master 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY