sudo: required
services:
  - docker

before_install:
  - docker build -t brianbeck/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true brianbeck/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Frontend"
  env: "Frontend-env"
  bucket-name: "elasticbeanstalk-us-east-1-651266901933"
  bucket-path: "Frontend"
  # only deploy on changes to master 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY